
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
 
namespace BBD.Models
{
	[Serializable] 
	public partial class tb_Emp_Hos
	{

		public tb_Emp_Hos MiniItem(bool isMini = true){
			return new tb_Emp_Hos(){

				Id = this.Id,

				emp_id = this.emp_id,

				hospid = this.hospid,

				creatorid = this.creatorid,

				creator = this.creator,

				c_time = this.c_time,

			};
		}
	}

}
