//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
 
namespace BBD.Models
{
	[Serializable] 
	public partial class tb_Hosp_Info
	{
		public tb_Hosp_Info MiniItem(bool isMini = true){
			return new tb_Hosp_Info(){
				HospId = this.HospId,
				Hname = this.Hname,
				address = this.address,
				MapUrl = this.MapUrl,
				tel = this.tel,
				sType = this.sType,
				traffic = this.traffic,
				grade = this.grade,
				state = this.state,
				CityId = this.CityId,
				C_Time = this.C_Time,
				CreatorId = this.CreatorId,
				ModLastTime = this.ModLastTime,
				intro = this.intro,
				ModfyId = this.ModfyId,
				IsDel = this.IsDel,
				PyShort = this.PyShort,
				PyLong = this.PyLong,
			};
		}
	}
}
