//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
 
namespace BBD.Models
{
	[Serializable] 
	public partial class tb_Sys_UserVipPermission
	{
		public tb_Sys_UserVipPermission MiniItem(bool isMini = true){
			return new tb_Sys_UserVipPermission(){
				vipId = this.vipId,
				vipUserId = this.vipUserId,
				VipPermission = this.VipPermission,
				vipRemark = this.vipRemark,
				vipIsdel = this.vipIsdel,
				vipAddtime = this.vipAddtime,
			};
		}
	}
}
