//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
 
namespace BBD.Models
{
	[Serializable] 
	public partial class tb_Sms_Down
	{
		public tb_Sms_Down MiniItem(bool isMini = true){
			return new tb_Sms_Down(){
				Id = this.Id,
				mobile = this.mobile,
				msg = this.msg,
				creatorId = this.creatorId,
				creator = this.creator,
				c_time = this.c_time,
				sendFlag = this.sendFlag,
				errMsg = this.errMsg,
				sendTime = this.sendTime,
				stype = this.stype,
				pipeId = this.pipeId,
				levelNum = this.levelNum,
				exId = this.exId,
				sysPlatform = this.sysPlatform,
				M_NO = this.M_NO,
			};
		}
	}
}
