//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
 
namespace BBD.Models
{
	[Serializable] 
	public partial class tb_Sys_UserInfo
	{
		public tb_Sys_UserInfo MiniItem(bool isMini = true){
			return new tb_Sys_UserInfo(){
				Uid = this.Uid,
				uDepid = this.uDepid,
				uLoginName = this.uLoginName,
				uPwd = this.uPwd,
				uGender = this.uGender,
				uIsDel = this.uIsDel,
				uPost = this.uPost,
				uRemark = this.uRemark,
				uAddtime = this.uAddtime,
				uMobile = this.uMobile,
				CityId = this.CityId,
				uName = this.uName,
			};
		}
	}
}
