
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
 
namespace BBD.Models
{
	[Serializable] 
	public partial class tb_Serv_Info
	{

		public tb_Serv_Info MiniItem(bool isMini = true){
			return new tb_Serv_Info(){

				ID = this.ID,

				ServId = this.ServId,

				ServName = this.ServName,

				ServMemo = this.ServMemo,

				ServType = this.ServType,

				state = this.state,

				price = this.price,

				CTime = this.CTime,

				CreatorId = this.CreatorId,

				Creator = this.Creator,

				IsDel = this.IsDel,

				LastModTime = this.LastModTime,

				ModifyId = this.ModifyId,

				HospId = this.HospId,

			};
		}
	}

}
