//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
 
namespace BBD.Models
{
	[Serializable] 
	public partial class tb_Sms_up
	{
		public tb_Sms_up MiniItem(bool isMini = true){
			return new tb_Sms_up(){
				id = this.id,
				mobile = this.mobile,
				msg = this.msg,
				C_time = this.C_time,
				S_time = this.S_time,
				PipeId = this.PipeId,
				CreatorId = this.CreatorId,
				M_no = this.M_no,
			};
		}
	}
}
