
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
 
namespace BBD.Models
{
	[Serializable] 
	public partial class tb_Sys_Permission
	{

		public tb_Sys_Permission MiniItem(bool isMini = true){
			return new tb_Sys_Permission(){

				pId = this.pId,

				pParentId = this.pParentId,

				pName = this.pName,

				pAreaName = this.pAreaName,

				pControllerName = this.pControllerName,

				pActionMenu = this.pActionMenu,

				pActionNum = this.pActionNum,

				PActionName = this.PActionName,

				pFormMethod = this.pFormMethod,

				pOperationType = this.pOperationType,

				pIco = this.pIco,

				pOrder = this.pOrder,

				pIsLink = this.pIsLink,

				pLinkUrl = this.pLinkUrl,

				pIsShow = this.pIsShow,

				pRemark = this.pRemark,

				pIsDel = this.pIsDel,

				pState = this.pState,

				pOperTime = this.pOperTime,

			};
		}
	}

}
