//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
 
namespace BBD.Models
{
	[Serializable] 
	public partial class tb_Sms_report
	{
		public tb_Sms_report MiniItem(bool isMini = true){
			return new tb_Sms_report(){
				id = this.id,
				mobile = this.mobile,
				C_time = this.C_time,
				R_time = this.R_time,
				pipeId = this.pipeId,
				errMsg = this.errMsg,
				M_no = this.M_no,
				S_time = this.S_time,
			};
		}
	}
}
