//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
 
namespace BBD.Models
{
	[Serializable] 
	public partial class tb_User_Info
	{
		public tb_User_Info MiniItem(bool isMini = true){
			return new tb_User_Info(){
				uId = this.uId,
				HospId = this.HospId,
				Name = this.Name,
				Female = this.Female,
				Birth = this.Birth,
				Mobile = this.Mobile,
				Email = this.Email,
				ComeFrom = this.ComeFrom,
				IndustryType = this.IndustryType,
				Height = this.Height,
				Weight = this.Weight,
				WC = this.WC,
				Hipline = this.Hipline,
				Thigh_Cir = this.Thigh_Cir,
				Qq = this.Qq,
				WeiXin = this.WeiXin,
				BMI = this.BMI,
				Enter_Code = this.Enter_Code,
				Self_code = this.Self_code,
				Cityid = this.Cityid,
				PicPath = this.PicPath,
				Myhope = this.Myhope,
				CreatorId = this.CreatorId,
				Creator = this.Creator,
				C_time = this.C_time,
			};
		}
	}
}
