
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
 
namespace BBD.Models
{
	[Serializable] 
	public partial class tb_Weight_Chg
	{

		public tb_Weight_Chg MiniItem(bool isMini = true){
			return new tb_Weight_Chg(){

				Id = this.Id,

				uId = this.uId,

				RecDate = this.RecDate,

				Hid = this.Hid,

				Weight = this.Weight,

				TouchFlag = this.TouchFlag,

				PicPath = this.PicPath,

				CreatorId = this.CreatorId,

				Creator = this.Creator,

				C_time = this.C_time,

			};
		}
	}

}
