//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Dict
    {
        public int Id { get; set; }
        public string KeyName { get; set; }
        public string KeyWords { get; set; }
        public string KeyValue { get; set; }
        public Nullable<double> Seq { get; set; }
        public Nullable<System.DateTime> C_Time { get; set; }
        public Nullable<int> state { get; set; }
        public string mark { get; set; }
    }
}
