
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace BBD.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Hosp_Info
{

    public int HospId { get; set; }

    public string Hname { get; set; }

    public string address { get; set; }

    public string MapUrl { get; set; }

    public string tel { get; set; }

    public Nullable<int> sType { get; set; }

    public string traffic { get; set; }

    public Nullable<int> grade { get; set; }

    public Nullable<int> state { get; set; }

    public string CityId { get; set; }

    public Nullable<System.DateTime> C_Time { get; set; }

    public Nullable<int> CreatorId { get; set; }

    public Nullable<System.DateTime> ModLastTime { get; set; }

    public string intro { get; set; }

    public Nullable<int> ModfyId { get; set; }

    public Nullable<int> IsDel { get; set; }

    public string PyShort { get; set; }

    public string PyLong { get; set; }

}

}
