
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace BBD.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Hei_Wei
{

    public int Id { get; set; }

    public string Female { get; set; }

    public Nullable<double> Height { get; set; }

    public Nullable<double> St_weight { get; set; }

    public Nullable<double> Pt_weight { get; set; }

    public Nullable<double> WC { get; set; }

    public Nullable<double> Hipline { get; set; }

    public Nullable<double> Thigh_Cir { get; set; }

    public Nullable<System.DateTime> C_time { get; set; }

}

}
