
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace BBD.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Sys_UserInfo
{

    public int Uid { get; set; }

    public Nullable<int> uDepid { get; set; }

    public string uLoginName { get; set; }

    public string uPwd { get; set; }

    public string uGender { get; set; }

    public Nullable<int> uIsDel { get; set; }

    public string uPost { get; set; }

    public string uRemark { get; set; }

    public Nullable<System.DateTime> uAddtime { get; set; }

    public string uMobile { get; set; }

    public string CityId { get; set; }

    public string uName { get; set; }

}

}
