//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Sms_Down
    {
        public long Id { get; set; }
        public string mobile { get; set; }
        public string msg { get; set; }
        public Nullable<int> creatorId { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> c_time { get; set; }
        public Nullable<int> sendFlag { get; set; }
        public string errMsg { get; set; }
        public Nullable<System.DateTime> sendTime { get; set; }
        public Nullable<int> stype { get; set; }
        public Nullable<int> pipeId { get; set; }
        public Nullable<int> levelNum { get; set; }
        public string exId { get; set; }
        public Nullable<int> sysPlatform { get; set; }
        public string M_NO { get; set; }
    }
}
