//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Sys_Permission
    {
        public int pId { get; set; }
        public int pParentId { get; set; }
        public string pName { get; set; }
        public string pAreaName { get; set; }
        public string pControllerName { get; set; }
        public Nullable<int> pActionMenu { get; set; }
        public string pActionNum { get; set; }
        public string PActionName { get; set; }
        public string pFormMethod { get; set; }
        public Nullable<int> pOperationType { get; set; }
        public string pIco { get; set; }
        public Nullable<int> pOrder { get; set; }
        public Nullable<int> pIsLink { get; set; }
        public string pLinkUrl { get; set; }
        public Nullable<int> pIsShow { get; set; }
        public string pRemark { get; set; }
        public Nullable<int> pIsDel { get; set; }
        public Nullable<int> pState { get; set; }
        public Nullable<System.DateTime> pOperTime { get; set; }
    }
}
