
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace BBD.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Sys_MenuInfo
{

    public int mId { get; set; }

    public string mNum { get; set; }

    public Nullable<int> mPId { get; set; }

    public string mText { get; set; }

    public string mUrl { get; set; }

    public string mIcon { get; set; }

    public Nullable<System.DateTime> mAddtime { get; set; }

    public string mState { get; set; }

    public Nullable<bool> mChecked { get; set; }

    public Nullable<double> mSeq { get; set; }

    public string mPerNum { get; set; }

    public Nullable<double> mOrderindex { get; set; }

}

}
