//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Serv_Info
    {
        public int ID { get; set; }
        public int ServId { get; set; }
        public string ServName { get; set; }
        public string ServMemo { get; set; }
        public string ServType { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> CTime { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public string Creator { get; set; }
        public Nullable<int> IsDel { get; set; }
        public Nullable<System.DateTime> LastModTime { get; set; }
        public Nullable<int> ModifyId { get; set; }
    }
}
