//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Sys_Department
    {
        public int DepId { get; set; }
        public Nullable<int> DepPId { get; set; }
        public string DepName { get; set; }
        public string Depremark { get; set; }
        public Nullable<int> DepIsDel { get; set; }
        public Nullable<System.DateTime> DepAddtime { get; set; }
        public string CityId { get; set; }
        public string DepNum { get; set; }
    }
}
