
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace BBD.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Sys_Notice
{

    public int Id { get; set; }

    public string Title { get; set; }

    public string Contents { get; set; }

    public Nullable<int> Hot { get; set; }

    public Nullable<double> Seq { get; set; }

    public Nullable<int> ClickNum { get; set; }

    public Nullable<int> IsDel { get; set; }

    public string Creator { get; set; }

    public Nullable<System.DateTime> C_Time { get; set; }

    public string ShowImgUrl { get; set; }

    public string FilePath { get; set; }

    public string FileName { get; set; }

    public Nullable<int> IsPush { get; set; }

}

}
