
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace BBD.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Sys_RolePermission
{

    public int rpId { get; set; }

    public int rpRId { get; set; }

    public int rpPId { get; set; }

    public Nullable<int> rpIsDel { get; set; }

    public Nullable<System.DateTime> rpAddtime { get; set; }

}

}
