
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace BBD.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Sms_Tpl
{

    public int Id { get; set; }

    public string sms { get; set; }

    public Nullable<int> state { get; set; }

    public Nullable<int> creatorid { get; set; }

    public string creator { get; set; }

    public Nullable<System.DateTime> c_time { get; set; }

}

}
