//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Sys_UserVipPermission
    {
        public int vipId { get; set; }
        public int vipUserId { get; set; }
        public int VipPermission { get; set; }
        public Nullable<int> vipRemark { get; set; }
        public Nullable<int> vipIsdel { get; set; }
        public Nullable<System.DateTime> vipAddtime { get; set; }
    }
}
