//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_User_Info
    {
        public int uId { get; set; }
        public Nullable<int> HospId { get; set; }
        public string Name { get; set; }
        public string Female { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string ComeFrom { get; set; }
        public string IndustryType { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> WC { get; set; }
        public Nullable<double> Hipline { get; set; }
        public Nullable<double> Thigh_Cir { get; set; }
        public string Qq { get; set; }
        public string WeiXin { get; set; }
        public Nullable<double> BMI { get; set; }
        public string Enter_Code { get; set; }
        public string Self_code { get; set; }
        public string Cityid { get; set; }
        public string PicPath { get; set; }
        public string Myhope { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> C_time { get; set; }
    }
}
