//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_User_Account
    {
        public int Id { get; set; }
        public int uId { get; set; }
        public Nullable<int> TouchFlag { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> delay { get; set; }
        public Nullable<int> creatorId { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> c_time { get; set; }
    }
}
