//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_User_Dislike_Food
    {
        public int id { get; set; }
        public int uId { get; set; }
        public string FoodType { get; set; }
        public string FoodName { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> C_time { get; set; }
    }
}
